version: '3.8'

services:
  postgis:
    image: postgis/postgis:13-3.1
    environment:
      POSTGRES_DB: bootcamp_db
      POSTGRES_USER: bootcamp_db
      POSTGRES_PASSWORD: bootcamp_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
