version: '3.8'

services:
  postgis:
    image: postgis/postgis:13-3.1
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  bootcamp_m_api:
    build:
      context: .
      dockerfile: compose/api/Dockerfile
    image: purplerain/bootcamp_m:latest
    volumes:
      - ./staticfiles:/code/staticfiles
    env_file:
      - .env
    depends_on:
      - postgis
      - redis

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    depends_on:
      - bootcamp_m_api
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./staticfiles:/static
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

volumes:
  postgres_data: