version: '3.8'

services:
  postgis:
    image: postgis/postgis:13-3.1
    environment:
      POSTGRES_DB: bootcamp_db
      POSTGRES_USER: bootcamp_user
      POSTGRES_PASSWORD: bootcamp_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  bootcamp_m_api:
    build:
      context: .
      dockerfile: compose/api/Dockerfile
    volumes:
      - .:/code
      - ./staticfiles:/code/staticfiles
    env_file:
      - env
    depends_on:
      - postgis

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    depends_on:
      - bootcamp_m_api
    volumes:
      - ./compose/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./staticfiles:/static

volumes:
  postgres_data: